language: node_js
node_js:
- "stable"

before_install:
- openssl aes-256-cbc -K $encrypted_f5972b810471_key -iv $encrypted_f5972b810471_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d

- tar -xzf credentials.tar.gz
- ls
- npm i -g yarn


install:
- yarn


script:
- yarn test

deploy:
  provider: gae
  keyfile: client-secret.json
  project: chat-eleon
